-- pob-web: Path of Building Web

package.path = package.path .. ";/app/root/lua/?.lua;/app/root/lua/?/init.lua"

unpack = table.unpack
loadstring = load

bit = {
    lshift = bit32.lshift,
    rshift = bit32.rshift,
    band = bit32.band,
    bor = bit32.bor,
    bxor = bit32.bxor,
    bnot = bit32.bnot,
    tobit = function(value)
        local normalized = value % 0x100000000
        return normalized >= 0x80000000 and normalized - 0x100000000 or normalized
    end,
}

if not setfenv then -- Lua 5.2
    -- based on http://lua-users.org/lists/lua-l/2010-06/msg00314.html
    -- this assumes f is a function
    local function findenv(f)
        local level = 1
        repeat
            local name, value = debug.getupvalue(f, level)
            if name == '(luajit-env)' then return level, value end
            level = level + 1
        until name == nil
        return nil end
    getfenv = function (f) return(select(2, findenv(f)) or _G) end
    setfenv = function (f, t)
        local level = findenv(f)
        if level then debug.setupvalue(f, level, t) end
        return f end
end

arg = {}

jit = {
  opt = {
    start = function() end,
    stop = function() end,
  }
}

local coroutineYield = coroutine.yield
coroutine.yield = function(...)
    RequestFrames(2)
    return coroutineYield(...)
end

-- Rendering
function SetClearColor(r, g, b, a)
end
function StripEscapes(text)
    return text:gsub("%^%d", ""):gsub("%^x%x%x%x%x%x%x", "")
end
function GetAsyncCount()
    return 0
end

-- General Functions
function SetCursorPos(x, y)
end
function ShowCursor(doShow)
end
function GetScriptPath()
    return "."
end
function GetRuntimePath()
    return ""
end
function GetUserPath()
    return "/app/user"
end
function GetCloudProvider(_)
    return nil, nil, nil
end
function SetWorkDir(path)
    print("SetWorkDir: " .. path)
end
function GetWorkDir()
    return ""
end
function LoadModule(fileName, ...)
    if not fileName:match("%.lua") then
        fileName = fileName .. ".lua"
    end
    local func, err = loadfile(fileName)
    if func then
        return func(...)
    else
        error("LoadModule() error loading '" .. fileName .. "': " .. err)
    end
end
function PLoadModule(fileName, ...)
    if not fileName:match("%.lua") then
        fileName = fileName .. ".lua"
    end
    local func, err = loadfile(fileName)
    if func then
        return PCall(func, ...)
    else
        error("PLoadModule() error loading '" .. fileName .. "': " .. err)
    end
end

local debug = require "debug"
function PCall(func, ...)
    local ret = { xpcall(func, debug.traceback, ...) }
    if ret[1] then
        table.remove(ret, 1)
        return nil, unpack(ret)
    else
        return ret[2]
    end
end

function ConPrintf(fmt, ...)
    -- Optional
    print(string.format(fmt, ...))
end
function ConPrintTable(tbl, noRecurse)
end
function ConExecute(cmd)
end
function ConClear()
end
function SpawnProcess(cmdName, args)
end
function SetProfiling(isEnabled)
end
function Restart()
end
function Exit()
end
function SetForeground()
end

--
-- pob-web translation layer (zh-rCN)
-- Loads per-file translation modules generated by tools/translate/sync-from-poecharm.py.
-- Each module mirrors a PoeCharm CSV file so coverage can be checked file-by-file.
-- The modules are merged in memory and DrawString / DrawStringWidth / DrawStringCursorIndex
-- are intercepted so English UI text is replaced with Chinese. Falls back to the original
-- text when no translation exists, so it never breaks the app.
--
local translateTable = {}
local translateManifestOk, translateManifest = pcall(require, "translate_manifest")
if translateManifestOk and type(translateManifest) == "table" then
    for _, file in ipairs(translateManifest) do
        local chunk, loadErr = loadfile("lua/" .. file)
        if chunk then
            local ok, data = pcall(chunk)
            if ok and type(data) == "table" then
                for k, v in pairs(data) do
                    translateTable[k] = v
                end
            else
                print("[translate] failed to load " .. file .. ": " .. tostring(data))
            end
        else
            print("[translate] failed to open " .. file .. ": " .. tostring(loadErr))
        end
    end
end

if next(translateTable) then
    -- PoB embeds colour/format codes (e.g. ^x808080) inside DrawString text.
    -- We strip them for lookup, but we must preserve leading codes so the
    -- translated text keeps the intended colour. Without this, Chinese labels
    -- render in whatever colour happened to be active (often black/dark grey).
    local function splitLeadingEscapes(text)
        local escapes = {}
        local rest = text
        while true do
            local esc, tail = rest:match("^(%^x%x%x%x%x%x)(.*)$")
            if not esc then
                esc, tail = rest:match("^(%^%d)(.*)$")
            end
            if esc then
                table.insert(escapes, esc)
                rest = tail
            else
                break
            end
        end
        return table.concat(escapes), rest
    end

    local function T(text)
        if type(text) ~= "string" then
            return text
        end
        local prefix, key = splitLeadingEscapes(text)
        key = StripEscapes(key)
        local translated = translateTable[key]
        if translated then
            return prefix .. translated
        end
        return text
    end

    local _DrawString = DrawString
    DrawString = function(x, y, align, height, font, text)
        return _DrawString(x, y, align, height, font, T(text))
    end

    local _DrawStringWidth = DrawStringWidth
    DrawStringWidth = function(height, font, text)
        return _DrawStringWidth(height, font, T(text))
    end

    local _DrawStringCursorIndex = DrawStringCursorIndex
    DrawStringCursorIndex = function(size, font, text, x, y)
        return _DrawStringCursorIndex(size, font, T(text), x, y)
    end
    print("[translate] zh-rCN layer ACTIVE")
else
    print("[translate] zh-rCN layer DISABLED: no translation modules loaded")
end

dofile("Launch.lua")

--
-- pob-web related custom code
--
local mainObject = GetMainObject()

-- Disable the check for updates because we can't update the app
mainObject["CheckForUpdate"] = function(this)
end

-- Install the error handler
local showErrMsg = mainObject["ShowErrMsg"]
mainObject["ShowErrMsg"] = function(self, msg, ...)
    OnError(string.format(msg, ...))
    showErrMsg(self, msg, ...)
end

-- Hide the check for updates button
local function installOAuthLogoutHook(buildMode)
    local importTab = buildMode.importTab
    local logoutButton = importTab and importTab.controls and importTab.controls.logoutApiButton
    if logoutButton and type(logoutButton.onClick) == "function" then
        local logout = logoutButton.onClick
        logoutButton.onClick = function(...)
            logout(...)
            OnOAuthLogout()
        end
    end
end

local onInit = mainObject["OnInit"]
mainObject["OnInit"] = function(self)
    onInit(self)
    self.main.controls.checkUpdate.shown = function()
        return false
    end
    local buildMode = self.main.modes["BUILD"]
    local initBuild = buildMode.Init
    buildMode.Init = function(build, ...)
        initBuild(build, ...)
        installOAuthLogoutHook(build)
    end
end

local function runCallback(name, ...)
    local callback = GetCallback(name)
    if callback then
        return callback(...)
    end
    if mainObject and type(mainObject[name]) == "function" then
        return mainObject[name](mainObject, ...)
    end
    error("runCallback: no handler for '" .. tostring(name) .. "'")
end

function loadBuildFromCode(code)
    if not mainObject.main then
        error("loadBuildFromCode: mainObject.main is nil")
    end

    -- Flush any pending state before import
    runCallback("OnFrame")

    if mainObject.main.mode ~= "BUILD" then
        mainObject.main:SetMode("BUILD", false, "")
        runCallback("OnFrame")
    end

    local importTab = mainObject.main.modes["BUILD"]
        and mainObject.main.modes["BUILD"].importTab
    if not importTab or not importTab.controls then
        error("loadBuildFromCode: import tab controls not available")
    end

    importTab.controls.importCodeIn:SetText(code, true)
    importTab.controls.importCodeMode.selIndex = 2
    importTab.controls.importCodeGo.onClick()

    -- Flush to process the import
    runCallback("OnFrame")
end

function getBuildCode()
    if not mainObject.main then
        error("getBuildCode: mainObject.main is nil")
    end

    local build = mainObject.main.modes["BUILD"]
    if not build then
        error("getBuildCode: not in BUILD mode")
    end

    local xmlText = build:SaveDB("code")
    if not xmlText then
        error("getBuildCode: SaveDB returned nil")
    end

    return common.base64.encode(Deflate(xmlText)):gsub("+","-"):gsub("/","_")
end
