-- pob-web: Path of Building Web

package.path = package.path .. ";/app/root/lua/?.lua;/app/root/lua/?/init.lua"

unpack = table.unpack
loadstring = load

bit = {
    lshift = bit32.lshift,
    rshift = bit32.rshift,
    band = bit32.band,
    bor = bit32.bor,
    bxor = bit32.bxor,
    bnot = bit32.bnot,
    tobit = function(value)
        local normalized = value % 0x100000000
        return normalized >= 0x80000000 and normalized - 0x100000000 or normalized
    end,
}

if not setfenv then -- Lua 5.2
    -- based on http://lua-users.org/lists/lua-l/2010-06/msg00314.html
    -- this assumes f is a function
    local function findenv(f)
        local level = 1
        repeat
            local name, value = debug.getupvalue(f, level)
            if name == '(luajit-env)' then return level, value end
            level = level + 1
        until name == nil
        return nil end
    getfenv = function (f) return(select(2, findenv(f)) or _G) end
    setfenv = function (f, t)
        local level = findenv(f)
        if level then debug.setupvalue(f, level, t) end
        return f end
end

arg = {}

jit = {
  opt = {
    start = function() end,
    stop = function() end,
  }
}

local coroutineYield = coroutine.yield
coroutine.yield = function(...)
    RequestFrames(2)
    return coroutineYield(...)
end

-- Rendering
function SetClearColor(r, g, b, a)
end
function StripEscapes(text)
    return text:gsub("%^%d", ""):gsub("%^x%x%x%x%x%x%x", "")
end
function GetAsyncCount()
    return 0
end

-- General Functions
function SetCursorPos(x, y)
end
function ShowCursor(doShow)
end
function GetScriptPath()
    return "."
end
function GetRuntimePath()
    return ""
end
function GetUserPath()
    return "/app/user"
end
function GetCloudProvider(_)
    return nil, nil, nil
end
function SetWorkDir(path)
    print("SetWorkDir: " .. path)
end
function GetWorkDir()
    return ""
end
function LoadModule(fileName, ...)
    if not fileName:match("%.lua") then
        fileName = fileName .. ".lua"
    end
    local func, err = loadfile(fileName)
    if func then
        return func(...)
    else
        error("LoadModule() error loading '" .. fileName .. "': " .. err)
    end
end
function PLoadModule(fileName, ...)
    if not fileName:match("%.lua") then
        fileName = fileName .. ".lua"
    end
    local func, err = loadfile(fileName)
    if func then
        return PCall(func, ...)
    else
        error("PLoadModule() error loading '" .. fileName .. "': " .. err)
    end
end

local debug = require "debug"
function PCall(func, ...)
    local ret = { xpcall(func, debug.traceback, ...) }
    if ret[1] then
        table.remove(ret, 1)
        return nil, unpack(ret)
    else
        return ret[2]
    end
end

function ConPrintf(fmt, ...)
    -- Optional
    print(string.format(fmt, ...))
end
function ConPrintTable(tbl, noRecurse)
end
function ConExecute(cmd)
end
function ConClear()
end
function SpawnProcess(cmdName, args)
end
function SetProfiling(isEnabled)
end
function Restart()
end
function Exit()
end
function SetForeground()
end

--
-- pob-web translation layer (zh-rCN)
-- Loads per-file translation modules generated by tools/translate/sync-from-poecharm.py.
-- Each module mirrors a PoeCharm CSV file so coverage can be checked file-by-file.
-- The modules are merged in memory and DrawString / DrawStringWidth / DrawStringCursorIndex
-- are intercepted so English UI text is replaced with Chinese. Falls back to the original
-- text when no translation exists, so it never breaks the app.
--
local translateTable = {}
-- 翻译模块加载调试开关：
--   环境变量 POE_TRANSLATE_DEBUG=1 或设置全局 translateDebug=true 时，
--   会逐文件打印加载详情；默认只打印一行汇总，避免刷屏。
local translateDebug = true
do
    local debugEnv = (os.getenv and os.getenv("POE_TRANSLATE_DEBUG")) or ""
    translateDebug = debugEnv == "1"
        or debugEnv == "true"
        or (type(_G.translateDebug) == "boolean" and _G.translateDebug)
end
local translateLoadedFiles = 0
local translateFailedFiles = 0
local translateTotalEntries = 0
local translateManifestOk, translateManifest = pcall(require, "translate_manifest")
if translateManifestOk and type(translateManifest) == "table" then
    for _, file in ipairs(translateManifest) do
        local chunk, loadErr = loadfile("lua/" .. file)
        if chunk then
            local ok, data = pcall(chunk)
            if ok and type(data) == "table" then
                local count = 0
                for k, v in pairs(data) do
                    translateTable[k] = v
                    count = count + 1
                end
                translateLoadedFiles = translateLoadedFiles + 1
                translateTotalEntries = translateTotalEntries + count
                if translateDebug then
                    print(string.format("[translate] loaded %s (%d entries)", file, count))
                end
            else
                translateFailedFiles = translateFailedFiles + 1
                print("[translate] failed to load " .. file .. ": " .. tostring(data))
            end
        else
            translateFailedFiles = translateFailedFiles + 1
            print("[translate] failed to open " .. file .. ": " .. tostring(loadErr))
        end
    end
end
print(string.format(
    "[translate] loaded %d modules, %d failed, %d total entries%s",
    translateLoadedFiles,
    translateFailedFiles,
    translateTotalEntries,
    translateDebug and " (verbose)" or " (set POE_TRANSLATE_DEBUG=1 for per-file details)"
))

if next(translateTable) then
    -- Case-insensitive mirror for matching strings that PoB uppercases
    -- (item affix lines are rendered in ALL CAPS while CSV keys are Title Case).
    local translateTableLower = {}
    for k, v in pairs(translateTable) do
        if type(k) == "string" then
            translateTableLower[k:lower()] = v
        end
    end

    -- Normalised-label mirror for stat-compare lines. CompareStatList renders
    -- bare labels ("+667.5 Average Hit (+133.5%)", "-110 Maximum Mana"), but the
    -- corpus stores most display-stat labels as "Label:" (BuildDisplayStats.csv)
    -- or in bracketed form "(maximum mana)" (CalcDefence.csv). PoeCharm's
    -- TranslateMatch normalises both sides the same way; do the same here:
    -- lowercase, strip brackets and trailing colons on key AND value.
    local function normLabel(s)
        s = s:lower():gsub("[%(%)]", "")
        s = s:gsub(":%s*$", "")
        s = s:gsub("^%s+", ""):gsub("%s+$", "")
        return (s)
    end
    local function normValue(s)
        s = s:gsub("^%((.*)%)$", "%1")
        s = s:gsub(":%s*$", "")
        return (s)
    end
    local fuzzyLabelTable = {}
    for k, v in pairs(translateTable) do
        if type(k) == "string" and (k:find("[%(%)]") or k:find(":")) then
            local nk = normLabel(k)
            if #nk > 0 and #nk <= 50 and fuzzyLabelTable[nk] == nil then
                fuzzyLabelTable[nk] = normValue(v)
            end
        end
    end

    -- PoB embeds colour/format codes (e.g. ^x808080) inside DrawString text.
    -- We strip them for lookup, but we must preserve leading codes so the
    -- translated text keeps the intended colour. Without this, Chinese labels
    -- render in whatever colour happened to be active (often black/dark grey).
    local function splitLeadingEscapes(text)
        local escapes = {}
        local rest = text
        while true do
            -- PoB colour codes are exactly ^xRRGGBB (6 hex digits). The exact
            -- count matters: a greedy match would also swallow label text that
            -- starts with a hex digit (e.g. "ES Leech/On Hit Rate").
            local esc, tail = rest:match("^(%^x%x%x%x%x%x%x)(.*)$")
            if not esc then
                esc, tail = rest:match("^(%^%d)(.*)$")
            end
            if esc then
                table.insert(escapes, esc)
                rest = tail
            else
                break
            end
        end
        return table.concat(escapes), rest
    end

    -- Upstream StripEscapes() matches a 7-digit ^x form, so it leaves the 6-digit
    -- ^xRRGGBB codes PoB actually uses in place and every coloured stat label
    -- misses the table. Strip the escape codes ourselves instead.
    local function stripEscapes(text)
        return text:gsub("%^%d", ""):gsub("%^x%x%x%x%x%x%x", "")
    end

    -- Item affix lines and flavour text are rendered as resolved strings
    -- (e.g. "+25% Chance to Block Spell Damage") rather than StatDescriber
    -- templates. Convert them back to "{0}% Chance to Block Spell Damage" form
    -- so we can look them up in the same statDescriptions translation table.
    local function resolveToTemplate(text)
        local values = {}
        local n = 0
        -- Ranges like (80-120) or (+80-120) become a single placeholder.
        local templ = text:gsub("%b()", function(s)
            n = n + 1
            values[n] = s
            return "@V" .. n .. "@"
        end)
        -- Remaining signed/unsigned numbers become placeholders.
        templ = templ:gsub("([%+%-]?%d+%.?%d*)", function(num)
            n = n + 1
            values[n] = num
            return "@V" .. n .. "@"
        end)
        -- Convert temporary markers to {0}, {1}, ...
        templ = templ:gsub("@V(%d+)@", function(i)
            return "{" .. (tonumber(i) - 1) .. "}"
        end)
        return templ, values
    end

    local function T(text)
        if type(text) ~= "string" then
            return text
        end
        local prefix, key = splitLeadingEscapes(text)
        key = stripEscapes(key)
        local translated = translateTable[key]
        if translated then
            return prefix .. translated
        end
        -- Item tooltip lines render the label inline with the value (e.g.
        -- "^x7F7F7FArmour: ^x8888FF960" -> key "Armour: 960"). Match the
        -- label portion before the first ":" so a single entry like
        -- ["Armour"] = "护甲" covers every current and future value.
        local labelPart = key:match("^(.-):")
        if labelPart then
            local labelTranslated = translateTable[labelPart]
            if labelTranslated then
                return prefix .. labelTranslated .. key:sub(#labelPart + 1)
            end
        end
        -- Skill gem tags and similar comma-separated lists are drawn as one
        -- string (e.g. "Spell, AoE, Fire, Duration"). Translate each tag.
        if key:find(", ") then
            local parts, allTranslated = {}, true
            for part in key:gmatch("([^,]+)") do
                part = part:match("^%s*(.-)%s*$")
                local partTr = translateTable[part] or translateTableLower[part:lower()]
                if not partTr then
                    allTranslated = false
                    break
                end
                table.insert(parts, partTr)
            end
            if allTranslated then
                if translateDebug then
                    print(string.format("[translate] LIST %q -> %q", key, table.concat(parts, ", ")))
                end
                return prefix .. table.concat(parts, ", ")
            end
        end
        -- Item mod / flavour lines are rendered in ALL CAPS but the CSV keys
        -- are Title Case. Turn "+25% CHANCE TO BLOCK SPELL DAMAGE" into
        -- "{0}% Chance to Block Spell Damage" and look it up case-insensitively.
        if key:find("[%d%%%(]") then
            local templ, values = resolveToTemplate(key)
            translated = translateTable[templ] or translateTableLower[templ:lower()]
            if translated then
                local result = translated:gsub("{(%d)}", function(i)
                    return values[tonumber(i) + 1] or ("{" .. i .. "}")
                end)
                if translateDebug then
                    print(string.format("[translate] TEMPLATE %q -> %q -> %q", key, templ, result))
                end
                return prefix .. result
            end
        end
        -- Stat compare lines (e.g. "+667.5 Average Hit (+133.5%)", "+3.9m AoE Radius")
        -- are built by Build.lua CompareStatList as "<value> <label>[ <percent>]".
        -- The label is a displayStats entry (SkillsTab/BuildDisplayStats CSVs), but
        -- the dynamic value glued in front of it defeats exact matching. Split the
        -- value (with optional unit letter like "m" or trailing "%"), translate the
        -- label and re-attach the value and the "(+x%)" comparison part.
        local numPart, rest = key:match("^([%+%-~]?[%d%.,]+%%?%a?)%s+(.+)$")
        if numPart then
            local pct = rest:match("%b()$")
            local label = pct and rest:sub(1, #rest - #pct) or rest
            label = label:match("^%s*(.-)%s*$")
            local labelTr = translateTable[label]
                or translateTableLower[label:lower()]
                or fuzzyLabelTable[normLabel(label)]
            if labelTr then
                local result = numPart .. " " .. labelTr .. (pct and (" " .. pct) or "")
                if translateDebug then
                    print(string.format("[translate] COMPARE %q -> %q", key, result))
                end
                return prefix .. result
            end
        end
        -- Compound labels without a colon (e.g. "Requires Level 60, 138 STR")
        -- fall back to the longest matching prefix.
        for i = #key - 1, 1, -1 do
            translated = translateTable[key:sub(1, i)]
            if translated then
                return prefix .. translated .. key:sub(i + 1)
            end
        end
        if translateDebug then
            print(string.format("[translate] MISS %q", key))
        end
        return text
    end

    -- Expose T() for the WrapString wrapper installed after Launch.lua (below):
    -- Tooltip:AddLine word-wraps long lines (e.g. gem descriptions) into fragments
    -- via main:WrapString, so those lines must be translated as a whole BEFORE the
    -- split, otherwise no fragment can match a full-text key.
    _G.__pobWebTranslate = T

    local _DrawString = DrawString
    DrawString = function(x, y, align, height, font, text)
        return _DrawString(x, y, align, height, font, T(text))
    end

    local _DrawStringWidth = DrawStringWidth
    DrawStringWidth = function(height, font, text)
        return _DrawStringWidth(height, font, T(text))
    end

    local _DrawStringCursorIndex = DrawStringCursorIndex
    DrawStringCursorIndex = function(size, font, text, x, y)
        return _DrawStringCursorIndex(size, font, T(text), x, y)
    end
    print("[translate] zh-rCN layer ACTIVE")
else
    print("[translate] zh-rCN layer DISABLED: no translation modules loaded")
end

dofile("Launch.lua")

--
-- pob-web translation layer: stat descriptions (item/skill mod text)
--
-- Stat descriptions ("Adds {0} to {1} Physical Damage to Attacks" etc.) are
-- stored as templates with placeholders and formatted by Modules/StatDescriber.lua
-- via a chain of gsub calls. By the time text reaches DrawString the placeholders
-- are already numbers, so the DrawString hook above can never match them. We
-- therefore translate the templates right here, after LoadModule loads the data
-- module and before StatDescriber formats it.
do
    local function normalise(text)
        -- "{0:+d}" / "{0:d}" -> "{0}" so it matches the simplified CSV entries
        return text:gsub("{(%d):(%+?)d}", "{%1}")
    end

    local function restore(translated, original)
        -- Put the "+d" style formatting back onto the translated template so the
        -- value keeps its sign when StatDescriber formats it.
        return (translated:gsub("{(%d)}", function(n)
            local sign = original:match("{" .. n .. ":(%+?)d}")
            if sign then
                return "{" .. n .. ":" .. sign .. "d}"
            end
            return "{" .. n .. "}"
        end))
    end

    local function translateText(text)
        local translated = translateTable[normalise(text)]
        if translated then
            return restore(translated, text)
        end
        return text
    end

    local function translateScope(tbl, seen)
        seen = seen or {}
        if seen[tbl] then return end
        seen[tbl] = true
        for _, v in pairs(tbl) do
            if type(v) == "table" then
                if type(v.text) == "string" then
                    local before = v.text
                    v.text = translateText(v.text)
                    if v.text ~= before and translateDebug then
                        print(string.format("[translate] STAT %q -> %q", before, v.text))
                    end
                end
                translateScope(v, seen)
            end
        end
    end

    if LoadModule then
        local _LoadModule = LoadModule
        LoadModule = function(fileName, ...)
            local results = { _LoadModule(fileName, ...) }
            local mod = results[1]
            if type(fileName) == "string" and fileName:match("^Data/StatDescriptions/") and type(mod) == "table" then
                local count = 0
                for _ in pairs(mod) do count = count + 1 end
                print(string.format("[translate] HOOK %s (%d top-level entries)", fileName, count))
                translateScope(mod)
            end
            return unpack(results)
        end
    end
end

--
-- pob-web related custom code
--
local mainObject = GetMainObject()

-- Disable the check for updates because we can't update the app
mainObject["CheckForUpdate"] = function(this)
end

-- Install the error handler
local showErrMsg = mainObject["ShowErrMsg"]
mainObject["ShowErrMsg"] = function(self, msg, ...)
    OnError(string.format(msg, ...))
    showErrMsg(self, msg, ...)
end

-- Translate whole lines before main:WrapString splits them. Tooltip:AddLine
-- word-wraps long text (gem/skill descriptions, flavour text) into per-line
-- fragments drawn by individual DrawString calls; translating the whole line
-- here (while the full sentence is still intact) lets whole-sentence keys hit.
local wrapString = mainObject["WrapString"]
if wrapString and _G.__pobWebTranslate then
    local translateLine = _G.__pobWebTranslate
    mainObject["WrapString"] = function(self, str, ...)
        if type(str) == "string" then
            str = translateLine(str)
        end
        return wrapString(self, str, ...)
    end
end

-- Hide the check for updates button
local function installOAuthLogoutHook(buildMode)
    local importTab = buildMode.importTab
    local logoutButton = importTab and importTab.controls and importTab.controls.logoutApiButton
    if logoutButton and type(logoutButton.onClick) == "function" then
        local logout = logoutButton.onClick
        logoutButton.onClick = function(...)
            logout(...)
            OnOAuthLogout()
        end
    end
end

local onInit = mainObject["OnInit"]
mainObject["OnInit"] = function(self)
    onInit(self)
    self.main.controls.checkUpdate.shown = function()
        return false
    end
    local buildMode = self.main.modes["BUILD"]
    local initBuild = buildMode.Init
    buildMode.Init = function(build, ...)
        initBuild(build, ...)
        installOAuthLogoutHook(build)
    end
end

local function runCallback(name, ...)
    local callback = GetCallback(name)
    if callback then
        return callback(...)
    end
    if mainObject and type(mainObject[name]) == "function" then
        return mainObject[name](mainObject, ...)
    end
    error("runCallback: no handler for '" .. tostring(name) .. "'")
end

function loadBuildFromCode(code)
    if not mainObject.main then
        error("loadBuildFromCode: mainObject.main is nil")
    end

    -- Flush any pending state before import
    runCallback("OnFrame")

    if mainObject.main.mode ~= "BUILD" then
        mainObject.main:SetMode("BUILD", false, "")
        runCallback("OnFrame")
    end

    local importTab = mainObject.main.modes["BUILD"]
        and mainObject.main.modes["BUILD"].importTab
    if not importTab or not importTab.controls then
        error("loadBuildFromCode: import tab controls not available")
    end

    importTab.controls.importCodeIn:SetText(code, true)
    importTab.controls.importCodeMode.selIndex = 2
    importTab.controls.importCodeGo.onClick()

    -- Flush to process the import
    runCallback("OnFrame")
end

function getBuildCode()
    if not mainObject.main then
        error("getBuildCode: mainObject.main is nil")
    end

    local build = mainObject.main.modes["BUILD"]
    if not build then
        error("getBuildCode: not in BUILD mode")
    end

    local xmlText = build:SaveDB("code")
    if not xmlText then
        error("getBuildCode: SaveDB returned nil")
    end

    return common.base64.encode(Deflate(xmlText)):gsub("+","-"):gsub("/","_")
end
